apiVersion: v2
name: mongodb-enterprise-operator
description: MongoDB Kubernetes Enterprise Operator deployment
version: 0.1.0
kubeVersion: '>=1.15-0'
keywords:
- mongodb
- database
- nosql
home: https://github.com/mongodb/helm-charts
maintainers:
- name: theburi
  email: belika@hotmail.com
