---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-crendential
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
    user: {{ .Values.opsManager.APIKey | b64enc }}
    publicApiKey: {{ .Values.opsManager.APISecret | b64enc }}
