---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-enterprise-database-pods
  {{- if not (eq (.Values.watchNamespace | default "*") "*") }}
  namespace: {{ .Values.watchNamespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
{{- if .Values.registry.imagePullSecrets}}
imagePullSecrets:
  - name: {{ .Values.registry.imagePullSecrets }}
{{- end }}
