apiVersion: v2
name: mongodb-enterprise-database
description: MongoDB Kubernetes Enterprise Operator- MongoDB DataBase charts
version: 0.1.1
kubeVersion: '>=1.15-0'
keywords:
- mongodb
- database
- nosql
home: https://github.com/mongodb/mongodb-enterprise-kubernetes
maintainers:
- name: theburi
  email: belika@hotmail.com
dependencies:
  - name: mongodb-enterprise-operator
    version: "0.1.*"
    repository: "https://mongodb.github.io/helm-charts"
    condition: mongodb-enterprise-operator.enabled
