## MongoDB Enterprise Database

# Set this to true if your cluster is managing SecurityContext for you.
# If running OpenShift (Cloud, Minishift, etc.), set this to true.
managedSecurityContext: false

# Section to describe components that needs to be installed
mongodb-enterprise-operator:
  enabled: true


# Optional configuration.
deployValidationWebhooks: true

name: mdbreplset
type: ReplicaSet
members: 3
opsManager:
  # Ops Manager connection could be configured  with Values and This HELM chart will create
  # nesessary Secret and Config Map.
  URL:
  orgid:
  APIKey:
  APISecret:
  # Alternatevly an existing secret and config map could be provided directly
  configMap: opsmanager-configmap
  secretRef: opsmanager-org-access-key
resources:
  limits:
    cpu: 2
    memory: 1.5G
  requests:
    cpu: 1
    memory: 1G
tolerations: []

clusterName: cluster.local

registry:
  imagePullSecrets:
  # TODO: specify for each image and move there?
  pullPolicy: Always
  # Specify if images are pulled from private registry
