apiVersion: v2
name: mongodb-atlas-operator-crds
description: MongoDB Atlas Operator CRDs - Helm chart for installing and upgrading Custom Resource Definitions (CRDs) for the Atlas Operator.
type: application
version: 0.1.0
appVersion: 0.4.0
kubeVersion: ">=1.15.0-0"
keywords:
  - mongodb
  - atlas
  - database
  - cluster
  - nosql
home: https://github.com/mongodb/mongodb-atlas-kubernetes
maintainers:
  - name: MongoDB
    email: support@mongodb.com
