apiVersion: v2
name: mongodb-atlas-operator
description: |-
  MongoDB Atlas Operator - a Helm chart for installing and upgrading Atlas Operator: the official Kubernetes operator allowing to manage MongoDB Atlas resources from Kubernetes
type: application
version: 0.2.0
appVersion: 0.5.0
kubeVersion: ">=1.15.0-0"
keywords:
  - mongodb
  - atlas
  - database
  - cluster
  - nosql
home: https://github.com/mongodb/mongodb-atlas-kubernetes
maintainers:
  - name: MongoDB
    email: support@mongodb.com
dependencies:
  - name: mongodb-atlas-operator-crds
    version: "0.2.0"
    repository: "https://mongodb.github.io/helm-charts"
    condition: mongodb-atlas-operator-crds.enabled
